### ISSUE TITLE
SendV2Activity crashes on start if there are no logged wallets in app

### ISSUE THREAD

**Issue by Alexandr1992** [O3Labs/O3Android#316]
This is not the usual case but SendV2Activity crashes if you need to start it without logged wallets. For example, from other application.

1. There are no logged wallets in application
2. Start activity SendV2Activity with extras "uri" and "assetID".
3. Actual result: Activity is crashed

**logs:**

> --------- beginning of crash
> 2019-06-27 14:31:45.785 4833-4833/? E/AndroidRuntime: FATAL EXCEPTION: main
> Process: network.o3.o3wallet, PID: 4833
> java.lang.RuntimeException: Unable to start activity ComponentInfo{network.o3.o3wallet/network.o3.o3wallet.Wallet.SendV2.SendV2Activity}: kotlin.KotlinNullPointerException
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
>     at android.app.ActivityThread.-wrap11(Unknown Source:0)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
>     at android.os.Handler.dispatchMessage(Handler.java:106)
>     at android.os.Looper.loop(Looper.java:171)
>     at android.app.ActivityThread.main(ActivityThread.java:6651)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
>  Caused by: kotlin.KotlinNullPointerException
>     at network.o3.o3wallet.NEP6.getDefaultAccount(NEP6.kt:135)
>     at network.o3.o3wallet.Account.restoreWalletFromDevice(Account.kt:189)
>     at network.o3.o3wallet.Account.getWallet(Account.kt:263)
>     at network.o3.o3wallet.Wallet.SendV2.SendViewModel.loadOwnedAssets(SendViewModel.kt:60)
>     at network.o3.o3wallet.Wallet.SendV2.SendViewModel.getOwnedAssets(SendViewModel.kt:50)
>     at network.o3.o3wallet.Wallet.SendV2.SendV2Activity$setWithAssetId$1.run(SendV2Activity.kt:61)
>     at android.app.Activity.runOnUiThread(Activity.java:6252)
>     at network.o3.o3wallet.Wallet.SendV2.SendV2Activity.setWithAssetId(SendV2Activity.kt:60)
>     at network.o3.o3wallet.Wallet.SendV2.SendV2Activity.parseQRPayload(SendV2Activity.kt:79)
>     at network.o3.o3wallet.Wallet.SendV2.SendV2Activity.onCreate(SendV2Activity.kt:52)
>     at android.app.Activity.performCreate(Activity.java:7088)
>     at android.app.Activity.performCreate(Activity.java:7079)
>     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
>     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
>     at android.os.Handler.dispatchMessage(Handler.java:106) 
>     at android.os.Looper.loop(Looper.java:171) 
>     at android.app.ActivityThread.main(ActivityThread.java:6651) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
>

**Comment by saltyskip** [comment]
What kind of behavior would you expect in this situation, just open up initial screen and allow user to make wallet?

**Comment by Alexandr1992** [comment]
I see two ways:
1. Your case: "just open up initial screen.."
2. Close SendV2Activity and return custom resultCode via "setResult" to handle the case in other activity
